spring.application.name=gabaritol

spring.datasource.url=jdbc:postgresql://localhost:5432/springbootdb
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.config.import=optional:file:.env[.properties]

api.security.token.secret=${TOKEN_SECURITY}
app.cors.allowed-origins=${DOMAINS_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent

abacatepay.api.key=${ABACATEPAY_API_KEY}
abacatepay.api.base-url=https://api.abacatepay.com/v2
abacatepay.webhook.secret=${ABACATEPAY_WEBHOOK_SECRET}