package api.gabaritol.ai.generation;


import org.springframework.stereotype.Service;

import api.gabaritol.ai.AIProvider;
import api.gabaritol.ai.gemini.GeneratedQuestionsBatchDTO;
import api.gabaritol.entities.exam.Difficulty;
import api.gabaritol.exceptions.raises.AIProviderException;
import lombok.RequiredArgsConstructor;
import tools.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
@RequiredArgsConstructor
public class QuestionGeneratorService {

    private final AIProvider aiProvider;
    private final ObjectMapper objectMapper;

    public GeneratedQuestionsBatchDTO generateQuestions(
        String topic, 
        String board, 
        Difficulty difficulty,
        int quantity, 
        String referenceContent
    ) {

        String prompt = buildPrompt(topic, board, difficulty, quantity, referenceContent);
        String rawResponse = aiProvider.generateContent(prompt);
        String cleanJson = extractJson(rawResponse);

        try {
            return objectMapper.readValue(cleanJson, GeneratedQuestionsBatchDTO.class);
        } catch (Exception e) {
            log.error("Failed to parse AI response as JSON. Raw response: {}", rawResponse, e);
            throw new AIProviderException("Failed to parse questions generated by AI.");
        }
    }

    private String buildPrompt(
        String topic, 
        String board, 
        Difficulty difficulty,
        int quantity, 
        String referenceContent
    ) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("Você é um gerador de questões para concursos públicos brasileiros.\n");
        prompt.append("Gere ").append(quantity).append(" questões de múltipla escolha ");
        prompt.append("sobre o tema \"").append(topic).append("\", ");
        prompt.append("no estilo da banca \"").append(board).append("\", ");
        prompt.append("com nível de dificuldade ").append(difficulty).append(".\n");

        if (referenceContent != null && !referenceContent.isBlank()) {
            prompt.append("Baseie as questões no seguinte material de referência:\n");
            prompt.append(referenceContent).append("\n");
        }

        prompt.append("""
            Responda APENAS com um JSON válido, sem nenhum texto adicional antes ou depois,
            sem marcações de bloco de código (não use ```), seguindo EXATAMENTE este formato:
            {
              "questions": [
                {
                  "statement": "texto do enunciado",
                  "options": [
                    {"label": "A", "text": "texto da alternativa", "correct": false},
                    {"label": "B", "text": "texto da alternativa", "correct": true},
                    {"label": "C", "text": "texto da alternativa", "correct": false},
                    {"label": "D", "text": "texto da alternativa", "correct": false}
                  ],
                  "explanation": "explicação do porquê a alternativa correta está certa"
                }
              ]
            }
            """);

        return prompt.toString();
    }

    private String extractJson(String rawResponse) {
        String trimmed = rawResponse.trim();
        if (trimmed.startsWith("```")) {
            trimmed = trimmed.replaceAll("^```json", "")
            .replaceAll("^```", "")
            .replaceAll("```$", "")
            .trim();
        }
        return trimmed;
    }
}