package api.gabaritol.ai.generation;


import org.springframework.stereotype.Service;

import api.gabaritol.ai.AIProvider;
import api.gabaritol.ai.gemini.GeneratedQuestionsBatchDTO;
import api.gabaritol.entities.exam.Difficulty;
import api.gabaritol.entities.exam.EducationLevel;
import api.gabaritol.exceptions.raises.AIProviderException;
import lombok.RequiredArgsConstructor;
import tools.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
@RequiredArgsConstructor
public class QuestionGeneratorService {

    private final AIProvider aiProvider;
    private final ObjectMapper objectMapper;

    public GeneratedQuestionsBatchDTO generateQuestions(
        String topic, 
        String board, 
        Difficulty difficulty, 
        EducationLevel educationLevel,
        int quantity, 
        String referenceContent
    ) {

        String prompt = buildPrompt(topic, board, difficulty, educationLevel, quantity, referenceContent);
        String rawResponse = aiProvider.generateContent(prompt);
        String cleanJson = extractJson(rawResponse);

        try {
            return objectMapper.readValue(cleanJson, GeneratedQuestionsBatchDTO.class);
        } catch (Exception e) {
            log.error("Failed to parse AI response as JSON. Raw response: {}", rawResponse, e);
            throw new AIProviderException("Failed to parse questions generated by AI.");
        }
    }

    private String buildPrompt(
        String topic, 
        String board, 
        Difficulty difficulty,
        EducationLevel educationLevel, 
        int quantity, 
        String referenceContent
    ) {
        StringBuilder prompt = new StringBuilder();

        prompt.append("Você é um gerador de questões educacionais em português do Brasil.\n");
        prompt.append("Contexto do público-alvo: ").append(describeEducationLevel(educationLevel)).append(".\n");
        prompt.append("Gere ").append(quantity).append(" questões de múltipla escolha ");
        prompt.append("sobre o tema \"").append(topic).append("\"");

        if (board != null && !board.isBlank()) {
            prompt.append(", no estilo de \"").append(board).append("\"");
        }

        prompt.append(", com nível de dificuldade ").append(difficulty).append(".\n");

        if (referenceContent != null && !referenceContent.isBlank()) {
            prompt.append("Baseie as questões no seguinte material de referência:\n");
            prompt.append(referenceContent).append("\n");
        }

        prompt.append("""
            Responda APENAS com um JSON válido, sem nenhum texto adicional antes ou depois,
            sem marcações de bloco de código (não use ```), seguindo EXATAMENTE este formato:
            {
            "questions": [
                {
                "statement": "texto do enunciado",
                "options": [
                    {"label": "A", "text": "texto da alternativa", "correct": false},
                    {"label": "B", "text": "texto da alternativa", "correct": true},
                    {"label": "C", "text": "texto da alternativa", "correct": false},
                    {"label": "D", "text": "texto da alternativa", "correct": false}
                ],
                "explanation": "explicação do porquê a alternativa correta está certa"
                }
            ]
            }

            IMPORTANTE - regras de qualidade para as alternativas (evite questões óbvias):
            1. Todas as alternativas devem ter comprimento e nível de detalhe SEMELHANTES entre si.
            Nunca deixe a alternativa correta visivelmente mais longa, mais técnica ou mais completa que as demais.
            2. Varie aleatoriamente a posição da resposta correta entre as questões (não deixe sempre em B ou C).
            3. Os distratores (alternativas erradas) devem representar erros conceituais plausíveis e comuns
            — como confusão entre conceitos parecidos, trocas de causa/efeito, ou pequenos deslizes técnicos —
            nunca afirmações absurdas, contraditórias ou fáceis de descartar à primeira vista.
            4. Evite palavras absolutas como "sempre", "nunca", "todos", "nenhum" nas alternativas,
            a menos que também apareçam de forma equilibrada nas alternativas erradas.
            5. Não repita palavras-chave do enunciado apenas na alternativa correta como "dica" indireta.
            6. As alternativas erradas devem ser tentadoras para quem domina parcialmente o assunto,
            não apenas obviamente falsas para quem não estudou nada.
        """);

        return prompt.toString();
    }

    private String describeEducationLevel(EducationLevel level) {
        return switch (level) {
            case ELEMENTARY_SCHOOL -> "ensino fundamental, com linguagem simples e acessível para crianças/adolescentes";
            case HIGH_SCHOOL -> "ensino médio, alinhado ao que é cobrado no ENEM e vestibulares";
            case UNDERGRADUATE -> "graduação universitária, com profundidade técnica e terminologia acadêmica";
            case PUBLIC_EXAM -> "concursos públicos brasileiros, seguindo o padrão de bancas organizadoras";
        };
    }

    private String extractJson(String rawResponse) {
        String trimmed = rawResponse.trim();
        if (trimmed.startsWith("```")) {
            trimmed = trimmed.replaceAll("^```json", "")
            .replaceAll("^```", "")
            .replaceAll("```$", "")
            .trim();
        }
        return trimmed;
    }
}